#!/bin/bash

# Current working directory need to be set to MP3 repository

# If given an argument 1, the test machine won't wait for gdb connection.
# If no argument is given or other value is given, the test machine will wait for gdb connection.
if [[ $1 -eq 1 ]]; then
    debug_cmd=""
else
    debug_cmd="-S"
fi

qemu-system-i386 \
    -hda "student-distrib/mp3.img" \
    -m 256 \
    -gdb tcp:127.0.0.1:1234 \
    ${debug_cmd} \
    -name mp3
