#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0;0m' # No Color

echo -e "${BLUE}[Start pushing files]${NC}"
# sleep 1


if ! ./391_push; then
    echo -e "${RED}[Failed to push files to devel machine]${NC}"
    exit 1
else
    echo -e "${GREEN}[Complete pushing files]${NC}"
fi
# sleep 1


echo -e "${BLUE}[Start compiling kernel]${NC}"
if ! ssh -t root@localhost -p 10022 "cd /home/user/mp3_group_30/student-distrib && make dep && sudo make"; then
    echo -e "${RED}[Failed to compile kernel on the devel machine]${NC}"
    exit 2
else
    echo -e "${GREEN}[Complete compiling kernel]${NC}"
fi
# sleep 1

echo -e "${BLUE}[Start fetching img]${NC}"
if ! ./391_fetch_img; then
    echo -e "${RED}[Failed to fetch img from devel machine]${NC}"
    exit 1
else
    echo -e "${GREEN}[Complete fetching img from devel machine]${NC}"
fi
# sleep 1

echo -e "${BLUE}[Start test machine]${NC}"
if [[ $1 -eq 1 ]]; then
    ./391_test_kernel_nodebug
else
    ./391_test_kernel
fi